// <auto-generated />
using System;
using FBS_CRUD_Generico.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FBS_Mantenimientos_Financial.Domain.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20200804162515_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FBS_CRUD_Generico.Entities.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaMaquina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSistema")
                        .HasColumnType("datetime2");

                    b.Property<string>("Llaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSchemma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuevosValores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViejosValores")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });
#pragma warning restore 612, 618
        }
    }
}
